name: Build & Publish Dev Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'labels/**'
      - '.github/workflows/publish-image.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/mgerhold/clang-p2996:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.description=Clang p2996 dev container
            org.opencontainers.image.license=Apache-2.0
